//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splintered_Universe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public Character()
        {
            this.CombatEncounterItems = new HashSet<CombatEncounterItem>();
        }
    
        public int CharacterId { get; set; }
        public string Name { get; set; }
        public int CampaignCampaignId { get; set; }
        public int UserUserId { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<CombatEncounterItem> CombatEncounterItems { get; set; }
    }
}
