//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splintered_Universe
{
    using System;
    using System.Collections.Generic;
    
    public partial class CombatEncounter
    {
        public CombatEncounter()
        {
            this.CombatEncounterItems = new HashSet<CombatEncounterItem>();
        }
    
        public int CombatEncounterId { get; set; }
        public int CampaignCampaignId { get; set; }
        public System.DateTime DateStartPlayed { get; set; }
        public string DateEndPlayed { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateOfEncounter { get; set; }
        public string CurrentAP { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual ICollection<CombatEncounterItem> CombatEncounterItems { get; set; }
    }
}
