//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splintered_Universe
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemAction
    {
        public SystemAction()
        {
            this.CombatEncounterItems = new HashSet<CombatEncounterItem>();
            this.SystemSkills = new HashSet<SystemSkill>();
        }
    
        public int SystemActionId { get; set; }
        public int BaseAPCost { get; set; }
        public int MinAPCost { get; set; }
        public int FatigueCost { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public string GMNotes { get; set; }
        public int SystemActionCategorySystemActionCategoryId { get; set; }
    
        public virtual ICollection<CombatEncounterItem> CombatEncounterItems { get; set; }
        public virtual SystemActionCategory SystemActionCategory { get; set; }
        public virtual ICollection<SystemSkill> SystemSkills { get; set; }
    }
}
