//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splintered_Universe
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemRule
    {
        public SystemRule()
        {
            this.Campaigns = new HashSet<Campaign>();
            this.SystemSkillCategories = new HashSet<SystemSkillCategory>();
            this.SystemStats = new HashSet<SystemStat>();
            this.SystemActionCategories = new HashSet<SystemActionCategory>();
        }
    
        public int SystemRuleId { get; set; }
        public string SystemName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Campaign> Campaigns { get; set; }
        public virtual ICollection<SystemSkillCategory> SystemSkillCategories { get; set; }
        public virtual ICollection<SystemStat> SystemStats { get; set; }
        public virtual ICollection<SystemActionCategory> SystemActionCategories { get; set; }
    }
}
