//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splintered_Universe
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemSkill
    {
        public int SystemSkillId { get; set; }
        public int SystemSkillCategorySystemSkillCategoryId { get; set; }
        public string Name { get; set; }
        public SkillDifficulty Difficulty { get; set; }
        public string Description { get; set; }
        public string GMNotes { get; set; }
        public int SystemStatSystemStatId { get; set; }
        public int SystemActionSystemActionId { get; set; }
    
        public virtual SystemStat SystemStat { get; set; }
        public virtual SystemSkillCategory SystemSkillCategory { get; set; }
        public virtual SystemAction SystemAction { get; set; }
    }
}
