//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splintered_Universe
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.CanBeGM = false;
            this.IsAdmin = false;
            this.Characters = new HashSet<Character>();
            this.Campaigns = new HashSet<Campaign>();
        }
    
        public int UserId { get; set; }
        public string LoginName { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public bool CanBeGM { get; set; }
        public bool IsAdmin { get; set; }
    
        public virtual ICollection<Character> Characters { get; set; }
        public virtual ICollection<Campaign> Campaigns { get; set; }
    }
}
