using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Http;

namespace Splintered_Universe
{
    public static class WebApiConfig
    {
        //Generated by MVC 4 template
        public static void Register(HttpConfiguration config)
        {
            config.Routes.MapHttpRoute(
                name: "DefaultApi",
                routeTemplate: "api/{controller}/{id}",
                defaults: new { id = RouteParameter.Optional }
            );
        }
    }
}
